### PR TITLE
Added some infrastructure Security Guides

### PR DESCRIPTION
**Pull request by Pdzly**
Adds some initial guides on firewall and securing/setting up ssh.

### CODE REVIEW

**Comment by Sh4d** [comment]
Thanks for the contribution! I'm not really sure we want to turn into a full general server setup guide though. There's a ton of resources out there with that sort of content already, and I think they can do it better than us. I worry that we'll turn into just another site with a ton of outdated guides that don't work in a few years when Ubuntu moves on from ufw to whatever's next.

I feel we would do better focusing on lemmy (and general Fediverse) specific topics. Guides on things like scaling lemmy to multiple containers, adding custom rules to nginx, setting up cloudflare tunnel, things like that.

Open to discussion on this!

**Comment by Pdzly** [comment]
But hosting lemmy/mastodon/pixelfed.... requires infrastructure and if everyone is just "too scared" or to inexperienced. This could be a starting point. With it the other guides like scaling lemmy would then in the future make more sense to "newbies" who want to try out to host lemmy for himself.

I would say basics of linux infrastructure should be added, as this is the basics. All the things you mentioned are "experienced" or "veteran" infra structure topics. I would like to have a guide for newbies that try to start hosting lemmy ( those dont need multiple docker images or cloudflare tunnel ).

**Comment by Sh4d** [comment]
Let's try and see how it goes.

On mobile so hard to check, but I think you need systemctl enable / start for ufw? I don't think it comes up on startup by default

**Comment by Pdzly** [comment]
@Sh4d yes correct its in the guide, second to last step as otherwise it could lead to unexpected behaviour. 
grafik

**Comment by Sh4d** [comment]
Build failed

https://github.com/fedecan-ca/fedecan.ca/actions/runs/10030299241

**Comment by cynber** [comment]
Added `.github/workflows/ci.yml` to check for build issues before merging

**Pull request merged**
